service: serverless-graphql

provider:
  name: azure
  location: West US

functions:
  graphql:
    handler: handler.graphql
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res

plugins:
  - serverless-azure-functions
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-package-external

custom:
  dotenv:
    path: ../.env
  packageExternal:
    external:
      - '../lib'
      - '../package.json'
