service: serverless-graphql

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 15
  logs:
    restApi: true

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-package-external

custom:
  dotenv:
    path: ../.env
  packageExternal:
    external:
      - '../lib'
      - '../package.json'
