service: serverless-graphql

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: handler.express
    events:
      - http:
          path: /
          method: post
  playground:
    handler: handler.express
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-package-external

custom:
  dotenv:
    path: ../.env
  packageExternal:
    external:
      - '../lib'
      - '../package.json'
